### ISSUE TITLE
Elasticsearch output does not support parent-child indexing 

### ISSUE THREAD

**Issue by vordoom** [logstash-plugins/logstash-output-elasticsearch#129]
Hi!

I might be wrong, but seems like current implementation of elasticsearch output does not support [parent-child indexing](http://www.elastic.co/guide/en/elasticsearch/guide/master/parent-child.html). This way relevant documents cannot be posted into elasticsearch via logstash.

It looks like required change in plugin is very small and can be achieved by additional parameter + slight code modification (according to [relevant documentation](http://www.elastic.co/guide/en/elasticsearch/guide/master/indexing-parent-child.html)). Not a ruby expert, but the change may look like following:

![elasticsearch-output](https://cloud.githubusercontent.com/assets/8515163/7474902/fe6d73c2-f34c-11e4-866e-cccd5a37fb71.png)

This is definitely enhancement, but kind of an easy win :)

Thank you.

**Comment by sumithub** [comment]
Hello,

I am new to logstash and ruby. I'm facing the same issue while indexing child docs. I tried above code as mentioned by Vordoom, but didn't make it to work.  Would appreciate if Vordroom or someone from the community could help in this regard.

Here's the mapping and code change suggested above

Elasticsearch Version: 1.50
Logstash Version: 1.5.0

Added below line of code inside elasticsearch.rb at line 426

 parent = @parent ? event.sprintf(@parent) : nil
    buffer_receive([event.sprintf(@action), { :_id => document_id, :_index => index, :_type => type, :_routing => routing, :_parent => parent }, event])

Installed the plugin after gem build inside standalone logstash

./bin/plugin install /home/vagrant/logstash-output-elasticsearch/logstash-output-elasticsearch-0.2.7-java.gem

Logstash configuration looks like below:

input {
  elasticsearch {
   hosts => ["localhost:9200"]
   index => "shop"
    size => 500
   scroll => "5m"
   docinfo => true
  }
}

filter {
 mutate {
  remove_field => [ "@version" ]
  remove_field => ["@timestamp"]
 }
}

output {
 elasticsearch {
   index => "shop_logstash"
   host => "localhost"
   protocol => "http"
   index_type => "%{[@metadata][_type]}"
   document_id => "%{[@metadata][_id]}"
   workers => 1
   manage_template => false
 }
 stdout { codec => rubydebug }
}

Index Structure : Shop is parent and variation is child type

PUT /shop/cloth/_mapping -d 
{
"cloth" : {
"properties" : {
"name" : {"type" : "string"}
}
}
}

PUT /shop/variation/_mapping
{
"variation" : {
"_parent" : { "type" : "cloth" },
"properties" : {
"size" : {"type" : "string", "index" : "not_analyzed"},
"color" : {"type" : "string", "index" : "not_analyzed"}
}
}
}

Logstash debug output

Logstash startup completed
output received {:event=>{"name"=>"Test shirt"}, :level=>:debug, :file=>"(eval)", :line=>"50", :method=>"output_func"}
{
    "name" => "Test shirt"
}
output received {:event=>{"color"=>"red", "size"=>"XXL"}, :level=>:debug, :file=>"(eval)", :line=>"50", :method=>"output_func"}
{
    "color" => "red",
     "size" => "XXL"
}
output received {:event=>{"color"=>"black", "size"=>"XL"}, :level=>:debug, :file=>"(eval)", :line=>"50", :method=>"output_func"}
{
    "color" => "black",
     "size" => "XL"
}

Flushing output {:outgoing_count=>3, :time_since_last_flush=>0.049, :outgoing_events=>{nil=>[["index", {:_id=>"1", :_index=>"shop_logstash", :_type=>"cloth", :_routing=>nil, :parent=>nil}, #<LogStash::Event:0x1ac862ce @metadata_accessors=#<LogStash::Util::Accessors:0x20a0cc47 @store={"_index"=>"shop", "_type"=>"cloth", "_id"=>"1", "retry_count"=>0}, @lut={"[_type]"=>[{"_index"=>"shop", "_type"=>"cloth", "_id"=>"1", "retry_count"=>0}, "_type"], "[_id]"=>[{"_index"=>"shop", "_type"=>"cloth", "_id"=>"1", "retry_count"=>0}, "_id"]}>, @cancelled=false, @data={"name"=>"Test shirt"}, @metadata={"_index"=>"shop", "_type"=>"cloth", "_id"=>"1", "retry_count"=>0}, @accessors=#<LogStash::Util::Accessors:0x325cf612 @store={"name"=>"Test shirt"}, @lut={"@version"=>[{"name"=>"Test shirt"}, "@version"], "@timestamp"=>[{"name"=>"Test shirt"}, "@timestamp"]}>>], ["index", {:_id=>"1000", :_index=>"shop_logstash", :_type=>"variation", :_routing=>nil, :parent=>nil}, #<LogStash::Event:0x6e6a4f7c @metadata_accessors=#<LogStash::Util::Accessors:0x1daf6765 @store={"_index"=>"shop", "_type"=>"variation", "_id"=>"1000", "retry_count"=>0}, @lut={"[_type]"=>[{"_index"=>"shop", "_type"=>"variation", "_id"=>"1000", "retry_count"=>0}, "_type"], "[_id]"=>[{"_index"=>"shop", "_type"=>"variation", "_id"=>"1000", "retry_count"=>0}, "_id"]}>, @cancelled=false, @data={"color"=>"red", "size"=>"XXL"}, @metadata={"_index"=>"shop", "_type"=>"variation", "_id"=>"1000", "retry_count"=>0}, @accessors=#<LogStash::Util::Accessors:0x602fb898 @store={"color"=>"red", "size"=>"XXL"}, @lut={"@version"=>[{"color"=>"red", "size"=>"XXL"}, "@version"], "@timestamp"=>[{"color"=>"red", "size"=>"XXL"}, "@timestamp"]}>>], ["index", {:_id=>"1001", :_index=>"shop_logstash", :_type=>"variation", :_routing=>nil, :parent=>nil}, #<LogStash::Event:0x262ec4ee @metadata_accessors=#<LogStash::Util::Accessors:0x218d711a @store={"_index"=>"shop", "_type"=>"variation", "_id"=>"1001", "retry_count"=>0}, @lut={"[_type]"=>[{"_index"=>"shop", "_type"=>"variation", "_id"=>"1001", "retry_count"=>0}, "_type"], "[_id]"=>[{"_index"=>"shop", "_type"=>"variation", "_id"=>"1001", "retry_count"=>0}, "_id"]}>, @cancelled=false, @data={"color"=>"black", "size"=>"XL"}, @metadata={"_index"=>"shop", "_type"=>"variation", "_id"=>"1001", "retry_count"=>0}, @accessors=#<LogStash::Util::Accessors:0x1a69dbae @store={"color"=>"black", "size"=>"XL"}, @lut={"@version"=>[{"color"=>"black", "size"=>"XL"}, "@version"], "@timestamp"=>[{"color"=>"black", "size"=>"XL"}, "@timestamp"]}>>]]}, :batch_timeout=>1, :force=>true, :final=>true, :level=>:debug, :file=>"stud/buffer.rb", :line=>"207", :method=>"buffer_flush"}
failed action with response of 400, dropping action: ["index", {:_id=>"1000", :_index=>"shop_logstash", :_type=>"variation", :_routing=>nil, :parent=>nil}, #<LogStash::Event:0x6e6a4f7c @metadata_accessors=#<LogStash::Util::Accessors:0x1daf6765 @store={"_index"=>"shop", "_type"=>"variation", "_id"=>"1000", "retry_count"=>0}, @lut={"[_type]"=>[{"_index"=>"shop", "_type"=>"variation", "_id"=>"1000", "retry_count"=>0}, "_type"], "[_id]"=>[{"_index"=>"shop", "_type"=>"variation", "_id"=>"1000", "retry_count"=>0}, "_id"]}>, @cancelled=false, @data={"color"=>"red", "size"=>"XXL"}, @metadata={"_index"=>"shop", "_type"=>"variation", "_id"=>"1000", "retry_count"=>0}, @accessors=#<LogStash::Util::Accessors:0x602fb898 @store={"color"=>"red", "size"=>"XXL"}, @lut={"@version"=>[{"color"=>"red", "size"=>"XXL"}, "@version"], "@timestamp"=>[{"color"=>"red", "size"=>"XXL"}, "@timestamp"]}>>] {:level=>:warn, :file=>"logstash/outputs/elasticsearch.rb", :line=>"451", :method=>"submit"}

failed action with response of 400, dropping action: ["index", {:_id=>"1001", :_index=>"shop_logstash", :_type=>"variation", :_routing=>nil, :parent=>nil}, #<LogStash::Event:0x262ec4ee @metadata_accessors=#<LogStash::Util::Accessors:0x218d711a @store={"_index"=>"shop", "_type"=>"variation", "_id"=>"1001", "retry_count"=>0}, @lut={"[_type]"=>[{"_index"=>"shop", "_type"=>"variation", "_id"=>"1001", "retry_count"=>0}, "_type"], "[_id]"=>[{"_index"=>"shop", "_type"=>"variation", "_id"=>"1001", "retry_count"=>0}, "_id"]}>, @cancelled=false, @data={"color"=>"black", "size"=>"XL"}, @metadata={"_index"=>"shop", "_type"=>"variation", "_id"=>"1001", "retry_count"=>0}, @accessors=#<LogStash::Util::Accessors:0x1a69dbae @store={"color"=>"black", "size"=>"XL"}, @lut={"@version"=>[{"color"=>"black", "size"=>"XL"}, "@version"], "@timestamp"=>[{"color"=>"black", "size"=>"XL"}, "@timestamp"]}>>] {:level=>:warn, :file=>"logstash/outputs/elasticsearch.rb", :line=>"451", :method=>"submit"}
Shifting current elasticsearch client {:level=>:debug, :file=>"logstash/outputs/elasticsearch.rb", :line=>"469", :method=>"flush"}
Switched current elasticsearch client to #0 at localhost {:level=>:debug, :file=>"logstash/outputs/elasticsearch.rb", :line=>"519", :method=>"shift_client"}
Plugin is finished {:plugin=><LogStash::Outputs::Stdout >, :level=>:info, :file=>"logstash/plugin.rb", :line=>"61", :method=>"finished"}
Pipeline shutdown complete. {:level=>:info, :file=>"logstash/pipeline.rb", :line=>"100", :method=>"run"}
Logstash shutdown completed

Just wondering if this issue is planned to be fixed in upcoming release? Thanks

**Comment by vordoom** [comment]
Hello sumithub,

You need to add relevant parameter in config section of the class:
```
config :parent, :validate => :string, :default => nil
```
Regards.

**Comment by sumithub** [comment]
Thanks Vordroom. Your solution did work. Now parent object is getting passed but elasticsearch is complaining about mapping parent not defined. Child document has _parent field defined for parent but logstash is flushing parent object. Need to figure out how to map parent:_type to _parent in logstash config file. Any ideas?

Got error to send bulk of actions: [400] {"error":"ElasticsearchIllegalArgumentException[Can't specify parent if no parent field has been configured]","status":400} {:level=>:error, :file=>"logstash/outputs/elasticsearch.rb", :line=>"467", :method=>"flush"}

**Comment by psaiz** [comment]
+1

**Comment by sumithub** [comment]
I resolved the issue of child documents not getting indexed by adding below mapping properties to child index.

"_routing": {
               "required": true,
               "path": "_parent"
            }
It did resolve the "failed action with response of 400, dropping action" issue.

**Comment by jimmyjones2** [comment]
@sumithub that won't work anymore with ES 2.0: https://www.elastic.co/guide/en/elasticsearch/reference/2.0/breaking_20_crud_and_routing_changes.html#_explicit_custom_routing

**Comment by yehosef** [comment]
+1 - I need this!

**Comment by yehosef** [comment]
I tried this with Logstash 2 copying from a ES1.7 cluster to a ES2.0 cluster.

Here's my file:
```
input {
    elasticsearch {
        hosts => ["es17_server"]
        index => "my_index"
        docinfo => true
        docinfo_fields => ["_index", "_type", "_id","_routing"]
    }
}
filter {
  mutate {
    remove_field =>["@timestamp"]
  }
}
output {
   elasticsearch {
       hosts    => ["es2_server"]
       workers  => 3
       flush_size =>2000
       index => "%{[@metadata][_index]}"
       document_type => "%{[@metadata][_type]}"
       document_id => "%{[@metadata][_id]}"
       routing => "%{[@metadata][_routing]}"
    }
}
```

I already had a template set up with the parent/child relations.  This seems to work fine.

**Comment by suyograo** [comment]
Fixed in https://github.com/logstash-plugins/logstash-output-elasticsearch/pull/307

**Comment by ShingleJ** [comment]
hello,  I also want to create child index, and my elasticsearch data is from oracle database,  but I can't understand `index_type => "%{[@metadata][_type]}"
document_id => "%{[@metadata][_id]}"`,  so I still can't make it work. how can I create the '_id' with parent-child relationship?
Here is my file:
```
input {
    jdbc {
        # Oracle jdbc connection string to our database, mydb
        # Oracle jdbc connection string to our database, mydb
        jdbc_connection_string => "jdbc:oracle:thin:@168.168.18.6:1523:odsuat"
        # The user we wish to execute our statement as
        jdbc_user => "kf111"
        jdbc_password => "kf111uat"
        # The path to our downloaded jdbc driver
        jdbc_driver_library => "/app/minglve/tools/elasticsearch-2.4.4/lib/ojdbc6.jar"
        # The name of the driver class for Oracle
        jdbc_driver_class => "Java::oracle.jdbc.driver.OracleDriver"
        # our query
        statement => "SELECT * from GPADMIN.EBC_OCRM_CUST_INFO"
    }
}

output {
  elasticsearch {
     hosts => ["168.61.9.167:9200"]
     index => "fromoracletest"
     document_type => "%{[@metadata][_type]}"
     document_id => "%{[@metadata][_id]}"
     workers => 1
    routing => "%{[@metadata][_routing]}"
 }
}
```
