### ISSUE TITLE
Failed to load class 'org.jruby.RubyObject$Access4JacksonDeserializer2f441575

### ISSUE THREAD

**Issue by Scratch-net** [logstash-plugins/logstash-output-elasticsearch#294]
ES 2.0, Logstash 2.0. I get this constantly

```
Attempted to send a bulk request to Elasticsearch configured at '["http://127.0.0.1:9200/"]', but an error occurred and it failed! Are you sure you can reach elasticsearch from this machine using the configuration provided? {:client_config=>{:hosts=>["http://127.0.0.1:9200/"], :ssl=>nil, :transport_options=>{:socket_timeout=>0, :request_timeout=>0, :proxy=>nil, :ssl=>{}}, :transport_class=>Elasticsearch::Transport::Transport::HTTP::Manticore, :logger=>nil, :tracer=>nil, :reload_connections=>false, :retry_on_failure=>false, :reload_on_failure=>false, :randomize_hosts=>false}, :error_message=>"Failed to load class 'org.jruby.RubyObject$Access4JacksonDeserializer2f441575': com.fasterxml.jackson.module.afterburner.ser.BeanPropertyAccessor", :error_class=>"JrJackson::ParseError", :backtrace=>["com/jrjackson/JrJacksonBase.java:83:in `generate'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/jrjackson-0.3.6/lib/jrjackson/jrjackson.rb:59:in `dump'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/multi_json-1.11.2/lib/multi_json/adapters/jr_jackson.rb:20:in `dump'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/multi_json-1.11.2/lib/multi_json/adapter.rb:25:in `dump'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/multi_json-1.11.2/lib/multi_json.rb:136:in `dump'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/elasticsearch-api-1.0.14/lib/elasticsearch/api/utils.rb:102:in `__bulkify'", "org/jruby/RubyArray.java:2414:in `map'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/elasticsearch-api-1.0.14/lib/elasticsearch/api/utils.rb:102:in `__bulkify'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/elasticsearch-api-1.0.14/lib/elasticsearch/api/actions/bulk.rb:82:in `bulk'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.1.2-java/lib/logstash/outputs/elasticsearch/http_client.rb:56:in `bulk'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.1.2-java/lib/logstash/outputs/elasticsearch.rb:353:in `submit'", "org/jruby/ext/thread/Mutex.java:149:in `synchronize'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.1.2-java/lib/logstash/outputs/elasticsearch.rb:350:in `submit'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.1.2-java/lib/logstash/outputs/elasticsearch.rb:382:in `flush'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.22/lib/stud/buffer.rb:219:in `buffer_flush'", "org/jruby/RubyHash.java:1342:in `each'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.22/lib/stud/buffer.rb:216:in `buffer_flush'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.22/lib/stud/buffer.rb:112:in `buffer_initialize'", "org/jruby/RubyKernel.java:1479:in `loop'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.22/lib/stud/buffer.rb:110:in `buffer_initialize'"], :level=>:error}
```

and then

```
Failed to flush outgoing items {:outgoing_count=>17, :exception=>"JrJackson::ParseError", :backtrace=>["com/jrjackson/JrJacksonBase.java:83:in `generate'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/jrjackson-0.3.6/lib/jrjackson/jrjackson.rb:59:in `dump'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/multi_json-1.11.2/lib/multi_json/adapters/jr_jackson.rb:20:in `dump'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/multi_json-1.11.2/lib/multi_json/adapter.rb:25:in `dump'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/multi_json-1.11.2/lib/multi_json.rb:136:in `dump'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/elasticsearch-api-1.0.14/lib/elasticsearch/api/utils.rb:102:in `__bulkify'", "org/jruby/RubyArray.java:2414:in `map'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/elasticsearch-api-1.0.14/lib/elasticsearch/api/utils.rb:102:in `__bulkify'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/elasticsearch-api-1.0.14/lib/elasticsearch/api/actions/bulk.rb:82:in `bulk'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.1.2-java/lib/logstash/outputs/elasticsearch/http_client.rb:56:in `bulk'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.1.2-java/lib/logstash/outputs/elasticsearch.rb:353:in `submit'", "org/jruby/ext/thread/Mutex.java:149:in `synchronize'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.1.2-java/lib/logstash/outputs/elasticsearch.rb:350:in `submit'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.1.2-java/lib/logstash/outputs/elasticsearch.rb:382:in `flush'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.22/lib/stud/buffer.rb:219:in `buffer_flush'", "org/jruby/RubyHash.java:1342:in `each'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.22/lib/stud/buffer.rb:216:in `buffer_flush'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.22/lib/stud/buffer.rb:112:in `buffer_initialize'", "org/jruby/RubyKernel.java:1479:in `loop'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.22/lib/stud/buffer.rb:110:in `buffer_initialize'"], :level=>:warn}
```

Only "hosts" is configured in "elasticsearch" output section.

I've tried to drop all indices/template from ES but it did not help. Had to fallback to elasticsearch_java

**Comment by haxorof** [comment]
+1
I experience the same issue just configuring hosts.
```
{
	: timestamp=>"2015-11-02T11:05:26.423000+0000",
	: message=>"Attempted to send a bulk request to Elasticsearch configured at '[\"http://localhost:9200/\"]', but an error occurred and it failed! Are you sure you can reach elasticsearch from this machine using the configuration provided?",
	: client_config=>{
		: hosts=>[
			"http://localhost:9200/"
		],
		: ssl=>nil,
		: transport_options=>{
			: socket_timeout=>0,
			: request_timeout=>0,
			: proxy=>nil,
			: ssl=>{}
		},
		: transport_class=>Elasticsearch: : Transport: : Transport: : HTTP: : Manticore,
		: logger=>nil,
		: tracer=>nil,
		: reload_connections=>false,
		: retry_on_failure=>false,
		: reload_on_failure=>false,
		: randomize_hosts=>false
	},
	: error_message=>"Failed to load class 'org.jruby.RubyObject$Access4JacksonDeserializer0056157c': com.fasterxml.jackson.module.afterburner.ser.BeanPropertyAccessor",
	: error_class=>"JrJackson::ParseError",
	: backtrace=>[
		"com/jrjackson/JrJacksonBase.java:83:in `generate'",
		"/opt/logstash/vendor/bundle/jruby/1.9/gems/jrjackson-0.3.6/lib/jrjackson/jrjackson.rb:59:in `dump'",
		"/opt/logstash/vendor/bundle/jruby/1.9/gems/multi_json-1.11.2/lib/multi_json/adapters/jr_jackson.rb:20:in `dump'",
		"/opt/logstash/vendor/bundle/jruby/1.9/gems/multi_json-1.11.2/lib/multi_json/adapter.rb:25:in `dump'",
		"/opt/logstash/vendor/bundle/jruby/1.9/gems/multi_json-1.11.2/lib/multi_json.rb:136:in `dump'",
		"/opt/logstash/vendor/bundle/jruby/1.9/gems/elasticsearch-api-1.0.14/lib/elasticsearch/api/utils.rb:102:in `__bulkify'",
		"org/jruby/RubyArray.java:2414:in `map'",
		"/opt/logstash/vendor/bundle/jruby/1.9/gems/elasticsearch-api-1.0.14/lib/elasticsearch/api/utils.rb:102:in `__bulkify'",
		"/opt/logstash/vendor/bundle/jruby/1.9/gems/elasticsearch-api-1.0.14/lib/elasticsearch/api/actions/bulk.rb:82:in `bulk'",
		"/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.1.2-java/lib/logstash/outputs/elasticsearch/http_client.rb:56:in `bulk'",
		"/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.1.2-java/lib/logstash/outputs/elasticsearch.rb:353:in `submit'",
		"org/jruby/ext/thread/Mutex.java:149:in `synchronize'",
		"/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.1.2-java/lib/logstash/outputs/elasticsearch.rb:350:in `submit'",
		"/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.1.2-java/lib/logstash/outputs/elasticsearch.rb:382:in `flush'",
		"/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.22/lib/stud/buffer.rb:219:in `buffer_flush'",
		"org/jruby/RubyHash.java:1342:in `each'",
		"/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.22/lib/stud/buffer.rb:216:in `buffer_flush'",
		"/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.22/lib/stud/buffer.rb:193:in `buffer_flush'",
		"/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.22/lib/stud/buffer.rb:159:in `buffer_receive'",
		"/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.1.2-java/lib/logstash/outputs/elasticsearch.rb:343:in `receive'",
		"/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.0.0-java/lib/logstash/outputs/base.rb:80:in `handle'",
		"(eval):103:in `output_func'",
		"/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.0.0-java/lib/logstash/pipeline.rb:252:in `outputworker'",
		"/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.0.0-java/lib/logstash/pipeline.rb:169:in `start_outputs'"
	],
	: level=>: error
}{
	: timestamp=>"2015-11-02T11:05:26.428000+0000",
	: message=>"Failed to flush outgoing items",
	: outgoing_count=>1,
	: exception=>"JrJackson::ParseError",
	: backtrace=>[
		"com/jrjackson/JrJacksonBase.java:83:in `generate'",
		"/opt/logstash/vendor/bundle/jruby/1.9/gems/jrjackson-0.3.6/lib/jrjackson/jrjackson.rb:59:in `dump'",
		"/opt/logstash/vendor/bundle/jruby/1.9/gems/multi_json-1.11.2/lib/multi_json/adapters/jr_jackson.rb:20:in `dump'",
		"/opt/logstash/vendor/bundle/jruby/1.9/gems/multi_json-1.11.2/lib/multi_json/adapter.rb:25:in `dump'",
		"/opt/logstash/vendor/bundle/jruby/1.9/gems/multi_json-1.11.2/lib/multi_json.rb:136:in `dump'",
		"/opt/logstash/vendor/bundle/jruby/1.9/gems/elasticsearch-api-1.0.14/lib/elasticsearch/api/utils.rb:102:in `__bulkify'",
		"org/jruby/RubyArray.java:2414:in `map'",
		"/opt/logstash/vendor/bundle/jruby/1.9/gems/elasticsearch-api-1.0.14/lib/elasticsearch/api/utils.rb:102:in `__bulkify'",
		"/opt/logstash/vendor/bundle/jruby/1.9/gems/elasticsearch-api-1.0.14/lib/elasticsearch/api/actions/bulk.rb:82:in `bulk'",
		"/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.1.2-java/lib/logstash/outputs/elasticsearch/http_client.rb:56:in `bulk'",
		"/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.1.2-java/lib/logstash/outputs/elasticsearch.rb:353:in `submit'",
		"org/jruby/ext/thread/Mutex.java:149:in `synchronize'",
		"/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.1.2-java/lib/logstash/outputs/elasticsearch.rb:350:in `submit'",
		"/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.1.2-java/lib/logstash/outputs/elasticsearch.rb:382:in `flush'",
		"/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.22/lib/stud/buffer.rb:219:in `buffer_flush'",
		"org/jruby/RubyHash.java:1342:in `each'",
		"/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.22/lib/stud/buffer.rb:216:in `buffer_flush'",
		"/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.22/lib/stud/buffer.rb:193:in `buffer_flush'",
		"/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.22/lib/stud/buffer.rb:159:in `buffer_receive'",
		"/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.1.2-java/lib/logstash/outputs/elasticsearch.rb:343:in `receive'",
		"/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.0.0-java/lib/logstash/outputs/base.rb:80:in `handle'",
		"(eval):103:in `output_func'",
		"/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.0.0-java/lib/logstash/pipeline.rb:252:in `outputworker'",
		"/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.0.0-java/lib/logstash/pipeline.rb:169:in `start_outputs'"
	],
	: level=>: warn
}
```

**Comment by suyograo** [comment]
Can you provide us a sample log line you pass through LS and gist the config, if you can?

**Comment by haxorof** [comment]
Here is the information you requested.

Received log entry via log-courier:
```
2015-11-02 12:43:39.244 [001] Info       BuildModule         BUILD NUMBER 123456 
```

/etc/logstash/conf.d/10-log-courier-output.conf
```
input {
  courier {
    port => 5001
    transport => "tcp"
    type => "log_courier"
  }
}
```

/etc/logstash/conf.d/20-elasticsearch-output.conf
```
output {
    elasticsearch {
	hosts => ["127.0.0.1:9200"]
    }
}
```

The running OS is CentOS 7.1 with OpenJDK 1.8.

**Comment by driskell** [comment]
@suyograo This seems to be some form of conflict in the newer JrJackson/Jackson that Logstash 2.0.0 (and possibly 1.5.something?) is loading.

Courier is using MultiJson which calls into JrJackson::Json with `:raw => true` so it returns fast Java Hash objects that quack like Ruby objects. This used to be perfectly fine before the JrJackson update..

It looks like in Logstash it has been changed to `JrJackson::Base`. When using this to serialise regular Ruby objects it works fine (generator with codec json for example). But when it needs to serialise Java objects that quack like Ruby objects it messes up. I've confirmed disabling `:raw` JrJackson dumping in the `courier` input plugin fixes the problem.

Still looking into it into hope can keep the raw though, but might have to drop it I guess.

**Comment by driskell** [comment]
Just updated the comment with some extra info. Located the exact field it fails on, `@timestamp`

**Comment by driskell** [comment]
Simple reproduction within Logstash (gonna look at outside it in a moment).

Config

```
input {
  generator {
    count => 1
    message => '{"message":"Hello World!"}'
    codec => json
  }
}
output {
  stdout {
    codec => json
  }
}
```

Modify logstash-core's lib/logstash/json.rb, so that `jruby_load` uses `JrJackson::Java` instead of `JrJackson::Ruby`. This makes the `generator` input plugin event hash a Java::Util::HashMap that quacks like a Ruby Hash, much like what happens with `courier` input plugin.

Running it will reproduce the `Failed to load class 'org.jruby.RubyObject$Access4JacksonDeserializer0056157c': com.fasterxml.jackson.module.afterburner.ser.BeanPropertyAccessor` exception.

**Comment by driskell** [comment]
Minimal reproduction case, with only JrJackson: https://gist.github.com/driskell/d11a988958b0185cf982
Download files and run: `bundle install --no-deployment --path vendor; jruby test.rb`
Tested with JRuby 1.7.6.

```
$ rvm use jruby
Using /Users/Jason/.rvm/gems/jruby-1.7.16
$ jruby test.rb
JrJackson::ParseError: Failed to load class 'org.jruby.RubyObject$Access4JacksonDeserializer45931591': com.fasterxml.jackson.module.afterburner.ser.BeanPropertyAccessor
  generate at com/jrjackson/JrJacksonBase.java:83
    (root) at test.rb:14
```

I shall mirror in the JrJackson repository

**Comment by suyograo** [comment]
Thanks much @driskell

**Comment by driskell** [comment]
I'm looking at releasing an update to Courier plugin soon to workaround this issue

**Comment by guyboertje** [comment]
@driskell - In v0.3.6 the pure ruby parse is faster that the old v0.2.9 raw parse, with the upside that Logstash does not break when plugins expect to be able to any method from the Hash and Array public methods but that our wrapper around the Java HashMap and ArrayList do not provide.

Please confirm, in Courier, that removing the raw option when parsing JSON indeed fixes the problem.  This is important because it makes a few method missing failures in other filters go away.  This also, makes Courier able to take advantage of other multi_json adapters (I know Thomas Enebo is working on a JSON library).

In the meantime I will fix this in JrJackson.

**Comment by driskell** [comment]
Hi @guyboertje - I can confirm not using `:raw` in the MultiJson adapter fixes the problem. If it's indeed faster I'll definitely make removal of that option permanent when loaded into newer Logstash.

I'd not heard of any other problems with filters and missing methods when using `:raw` in earlier versions but its certainly possible those got raised in the filter repositories and never were linked back to me. Do you think it's worth removing `:raw` for all Logstash versions? If it has caused some frustrating issues in other filters in the past then maybe the (possibly small) perf boost in using it isn't worth it at all, ever.

Thanks!

**Comment by guyboertje** [comment]
@driskell - I did not mean to indicate that the method missing failure are attributable to your plugin - your code mirrored what we were doing before so any input that parsed JSON strings with raw would return Events that some filters had problems with.
Filters and Outputs e.g. mutate called compact and delete_if etc on the wrapped Java Collection objects and these methods were missing.

With the change to using proper JRuby Hash and Array in LS 2.0 these kinds of bugs go away.

**Comment by guyboertje** [comment]
@driskell - we have only backported the JrJackson v0.3.6 to LS v1.5.5 - so IMO you need only support that older version and v2.

Further, I suspect there may be more problems if you load a newer version of JrJackson via multi_json (using Jackson 2.6.1) and LS wants an older version (using older Jackson code) and maybe issues with Java class loading.

**Comment by guyboertje** [comment]
@Scratch-net - please confirm that you are using the Courier input too.

**Comment by driskell** [comment]
@guyboertje Thanks for the info! I think what I will do is possibly just use the internal Logstash JSON functionality, which should bring the plugin in line with all other Elastic-maintained plugins in how JSON is handled.

**Comment by dixitk13** [comment]
same issue I believe, right?

```javascript
{
	:timestamp=>"2015-11-04T17:19:53.869000+0000", 
	:message=>"Attempted to send a bulk request to Elasticsearch configured at '[\"http://xx.xx.xx.xx:9200/\", \"http://xx.xx.xx.xx:9200/\"]',
	but an error occurred and it failed! Are you sure you can reach elasticsearch from this machine using the configuration provided?", 
	:client_config=>{:hosts=>["http://xx.xx.xx.xx:9200/", "http://xx.xx.xx.xx:9200/"], 
	:ssl=>nil, 
	:transport_options=>{
		:socket_timeout=>0, 
		:request_timeout=>0, 
		:proxy=>nil, 
		:ssl=>{}}, 
		:transport_class=>Elasticsearch::Transport::Transport::HTTP::Manticore, 
		:logger=>nil, 
		:tracer=>nil, 
		:reload_connections=>false, 
		:retry_on_failure=>false, 
		:reload_on_failure=>false, 
		:randomize_hosts=>false
		}, 
		:error_message=>"Failed to load class 'org.jruby.RubyObject$Access4JacksonDeserializer34491575': com.fasterxml.jackson.module.afterburner.ser.BeanPropertyAccessor", 
		:error_class=>"JrJackson::ParseError", 
		:backtrace=>["com/jrjackson/JrJacksonBase.java:83:in `generate'", 
		"/opt/logstash-2.0.0/vendor/bundle/jruby/1.9/gems/jrjackson-0.3.6/lib/jrjackson/jrjackson.rb:59:in `dump'", 
		"/opt/logstash/vendor/bundle/jruby/1.9/gems/multi_json-1.11.2/lib/multi_json/adapters/jr_jackson.rb:20:in `dump'",
		"/opt/logstash/vendor/bundle/jruby/1.9/gems/multi_json-1.11.2/lib/multi_json/adapter.rb:25:in `dump'", 
		"/opt/logstash/vendor/bundle/jruby/1.9/gems/multi_json-1.11.2/lib/multi_json.rb:136:in `dump'", 
		"/opt/logstash/vendor/bundle/jruby/1.9/gems/elasticsearch-api-1.0.14/lib/elasticsearch/api/utils.rb:102:in `__bulkify'", 
		"org/jruby/RubyArray.java:2414:in `map'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/elasticsearch-api-1.0.14/lib/elasticsearch/api/utils.rb:102:in `__bulkify'", 
		"/opt/logstash/vendor/bundle/jruby/1.9/gems/elasticsearch-api-1.0.14/lib/elasticsearch/api/actions/bulk.rb:82:in `bulk'", 
		"/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.1.2-java/lib/logstash/outputs/elasticsearch/http_client.rb:56:in `bulk'", 
		"/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.1.2-java/lib/logstash/outputs/elasticsearch.rb:353:in `submit'", 
		"org/jruby/ext/thread/Mutex.java:149:in `synchronize'", 
		"/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.1.2-java/lib/logstash/outputs/elasticsearch.rb:350:in `submit'", 
		"/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.1.2-java/lib/logstash/outputs/elasticsearch.rb:382:in `flush'", 
		"/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.22/lib/stud/buffer.rb:219:in `buffer_flush'", "org/jruby/RubyHash.java:1342:in `each'", 
		"/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.22/lib/stud/buffer.rb:216:in `buffer_flush'", 
		"/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.22/lib/stud/buffer.rb:193:in `buffer_flush'", 
		"/opt/logstash/vendor/bundle/jruby/1.9/gems/stud-0.0.22/lib/stud/buffer.rb:159:in `buffer_receive'", 
		"/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-2.1.2-java/lib/logstash/outputs/elasticsearch.rb:343:in `receive'", 
		"/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.0.0-java/lib/logstash/outputs/base.rb:80:in `handle'", 
		"/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-core-2.0.0-java/lib/logstash/outputs/base.rb:71:in `worker_setup'"], 
	:level=>:error
}	
```

**Comment by Scratch-net** [comment]
@guyboertje Yep, I use courier input

**Comment by ThomasdOtreppe** [comment]
The exact same error described on the top post happen to me too with 2.0 but I don't use Courrier. I have 2 file inputs (plain) and 2 RabbitMQ inputs. With the exception of geoip, filters only apply for the 2 file input (to parse them).

Here is my output if it's any useful:

```
output {
        elasticsearch {
                hosts => [ localhost ]
        }
}
```

**Comment by guyboertje** [comment]
I need to look at the RabbitMQ input too.

**Comment by ThomasdOtreppe** [comment]
```
input {
        # some info
        rabbitmq {
                queue => "logstash_queue"
                host => "192.168.0.2"
                exchange => "logstash"
        }
}
```

**Comment by ThomasdOtreppe** [comment]
I don't know if it matters, but I'm using the official JDK 8 from Oracle.

**Comment by tomsommer** [comment]
I'm using redis input, same problem

**Comment by guyboertje** [comment]
Fixed JrJackson in v0.3.7.
Will Update LogStash.

**Comment by ThomasdOtreppe** [comment]
Seems like it was geoip was the issue (as explained on #298) and filtering on N/A helped. However, I now noticed another issue due to somes iptables logs generating "IP1,IP2" in a field I do geoip on (never saw that before) and I'll open a bug for that.

**Comment by guyboertje** [comment]
@ThomasdOtreppe - this bug is very different from yours. All is explained in #298.

**Comment by riguy724** [comment]
Hey guys I'm still getting this with logstash 2.0. Any update on the status of this issue?

**Comment by romankor** [comment]
Have the same problem with input RabbitMq ( logstash 2.1 )

**Comment by guyboertje** [comment]
**NOTE to All - This issue is open because the fault explained below seems to be associated with this plugin but it is not. The cause lies in an input, codec or filter plugin.**

The original fault `Failed to load class 'org.jruby.RubyObject$Access4JacksonDeserializer` has been fixed.

However this error masked the real problem.  Some outputs need to serialize LS Events into JSON. Our JSON processor (JrJackson) can only serialize certain kinds of Ruby Objects.  It knows how to serialize a LS Event but because its a nested structure the values inside the Event need serialization too.  In some cases a 'rogue' object, i.e. that can't serialize, will get into the Event - causing a failure in the output.

Somewhere in the LS log output you should see `Cannot serialize instance of: {some Ruby Class name}`.  I need to know what that Ruby Class is to fix the problem. I also need to know your config.

@riguy724, @romankor - please post your error messages ^ and config here.

**Comment by guyboertje** [comment]
Closing in favour of https://github.com/elastic/logstash/issues/5200
